# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool: Default
  
strategy:
  matrix:
    Python312:
      PYTHON_VERSION: '3.12.10'
  maxParallel: 1

steps:
- task: PowerShell@2
  displayName: 'Instalar dependencias'
  inputs:
    targetType: 'inline'
    pwsh: false
    errorActionPreference: 'Stop'
    script: |
      Set-ExecutionPolicy Bypass -Scope Process
      python --version
      python -m pip install --upgrade pip
      pip install -r requirements.txt

- task: PowerShell@2
  displayName: 'Ejecutar tests'
  inputs:
    targetType: 'inline'
    pwsh: false
    errorActionPreference: 'Stop'
    script: |
      Set-ExecutionPolicy Bypass -Scope Process
      python manage.py test

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Python $(PYTHON_VERSION)'
  condition: succeededOrFailed()
