# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  name: 'Default' 
  
strategy:
  matrix:
    Python312:
      PYTHON_VERSION: '3.12.10'
  maxParallel: 1

steps:
# 0. Prependpath para asegurar el Python “real” del tool cache
- script: |
    echo "##vso[task.prependpath]C:\Users\ASUS TUF\agent\_work\_tool\Python\3.12.10\x64"
  displayName: 'Añadir Python real al PATH'

# 1. Crear y activar un venv
- script: |
    python -m venv .venv
    call .venv\Scripts\activate

    # Verificamos
    python --version
    where python
  displayName: 'Crear y activar venv'

# 2. Instalar dependencias dentro del venv
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Instalar dependencias en venv'
  failOnStderr: false

# 3. Ejecutar tests
- script: |
    call .venv\Scripts\activate
    python manage.py test
  displayName: 'Ejecutar tests en venv'
