# Generated by Django 5.2 on 2025-05-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
